- README.md
- index.js
- package-lock.json
- package.json
- src/cli.js
In case you just want to see what's happening with the modules list but you don't want to exit with an error, the `--no-errors` flag can be useful. (turns all errors into warnings)
> Adding --no-errors flag

- package-lock.json
- package.json
- src/lib/format.js
- src/lib/npm.js
- src/plugins/licenseTree.js
- src/plugins/maintenance.js
This PR tries to solve #22 #20 
- When everything goes well npcheck will output a custom message: `deasync@0.1.21 has been installed.`
- When something goes wrong with the NPM installation the cli will output `Failed to download module`, will skip the rest of the checks and will pipe the NPM output to `npcheck-errors.log`
Tested with node 15.x, node 16.x, npm 6.x and npm 7.x
> Handling the NPM output

- package-lock.json
- package.json
- src/plugins/license.js
This PR enables the license rules to apply also to the top-level modules (aka the modules that the ref-arch suggests)
> Adding license rules to top-level modules

- src/lib/result.js
- src/plugins/archive.js
- src/plugins/deprecation.js
- src/plugins/license.js
- src/plugins/licenseTree.js
- src/plugins/maintenance.js
- src/plugins/support.js
- src/plugins/tests.js
While writing some unit tests I realized that the names `error` and `passThroughError` are bad name choices for the work they're doing. 
So this PR renames the `error` to `createError` and `passThroughError` to `createWarning`. Now I believe it makes more sense for someone looking at the code.
> Refactoring

- test/plugins/license.test.js
- test/plugins/licenseTree.test.js
- test/plugins/maintenance.test.js
- test/plugins/support.test.js
This PR includes unit tests for the following plugins:
- Maintenance
- License
- LicenseTree
- Support
* I haven't written any tests (yet) for the `testPlugin` because I think I can rewrite the plugin in a simpler way.
> Adding another batch of unit tests

- src/plugins/deprecation.js
- src/plugins/maintenance.js
- src/plugins/support.js
- test/plugins/deprecation.test.js
- test/plugins/maintenance.test.js
- test/plugins/support.test.js
This PR includes fixes for the following issues:
- #31 
- #32 
- #33 
The package-support targets are now the following: `['all', 'lts', 'active', 'lts_active', 'supported']`
@mhdawson is there any target I forgot to add to the list ??
> Fixing known npcheck issues

- src/plugins/license.js
- test/plugins/license.test.js
This PR solves the following issue when the package license is defined as an array instead of a string.
> License field defined as an array

- src/cli.js
- src/lib/network.js
- src/plugins/archive.js
- src/plugins/tests.js
- src/plugins/typings.js
- test/lib/fetch.test.js
- test/plugins/archive.test.js
> Adding typescript typings plugin

- .github/workflows/nodejs-ci-action.yml
- package-lock.json
- package.json
- src/cli.js
- src/lib/network.js
- src/plugins/archive.js
- src/plugins/tests.js
- src/plugins/typings.js
- test/lib/fetch.test.js
- test/plugins/archive.test.js
> TypeError when GitHub URL is not defined #52

- package-lock.json
- package.json
As per this deprecation warning from `npm install`:
```
npm WARN deprecated eslint-plugin-standard@5.0.0: standard 16.0.0 and eslint-config-standard 16.0.0 no longer require the eslint-plugin-standard package. You can remove it from your dependencies with 'npm rm eslint-plugin-standard'. More info here: https://github.com/standard/standard/issues/1316
```
> chore: remove no longer required eslint-plugin-standard

- src/cli.js
If a module fails to install, clean up the env directory before
attempting the next module.
> fix: clean up env directory after failure

- src/lib/network.js
- test/lib/fetch.test.js
Return only the response data on cache hits for consistency with
non-cache hits.
> fix: return response data for cache hits

- src/lib/network.js
- src/plugins/typings.js
- test/plugins/archive.test.js
- test/plugins/typings.test.js
I also introduced the `ignore_cache` boolean option only to be used with unit tests since declaring the cache at the top (https://github.com/nodeshift/npcheck/blob/main/src/plugins/typings.js#L5) works fine when running the npcheck CLI but completely breaks the unit tests.
> Typings plugin unit tests

- package-lock.json
- package.json
- src/cli.js
- src/lib/network.js
- src/lib/npm.js
- src/plugins/archive.js
- src/plugins/audit.js
- src/plugins/licenseTree.js
- test/lib/fetch.test.js
- test/lib/npm.test.js
- test/plugins/audit.test.js
You can test the plugin using the following config. #58
```
{
"modules": [
{
"name": "js-extend",
"npmlink": "https://www.npmjs.com/package/js-extend"
},
{
"name": "normalize-url",
"npmlink": "https://www.npmjs.com/package/normalize-url"
}
],
"licenses": {
"allow": ["MIT", "Apache-2.0", "ISC", "BSD-2-Clause", "BSD-3-Clause"],
"rules": {}
}
}
```
Expected output:
```
Running checks on js-extend
Downloading module dependencies...
js-extend@1.0.1 has been installed.
Checking if it's deprecated on NPM                                PASS
Checking if github repository is archived                         PASS
Checking top-level license                                        PASS
Checking if module has appropriate testing                        PASS
continuous-integration/travis-ci/push
The …
```
> Adding NPM audit plugin

- package.json
- src/plugins/citgm.js
- test/plugins/citgm.test.js
Currently it does not seem like the eslint run script is checking any
files. This commit adds the current directory to the eslint command
and fixes a few or the lint issues that were reported.
> enable lint for pretest run script

- src/plugins/audit.js
- test/plugins/audit.test.js
The previous way of fetching https://npmjs.com/advisories/ URLs with
a `X-Spiferack: 1` header no longer returns JSON, most probably due
to such URLs now redirecting to the GitHub Advisory database. Switch
instead to use the endpoint:
`https://registry.npmjs.org/-/npm/v1/security/advisories/{id}`
Fixes: https://github.com/nodeshift/nodejs-reference-architecture/issues/94
> fix: update security advisory data endpoint

- src/cli.js
To help to quickly identify the errors when looking at the summary
```
NPCheck Report
(1): The module "kafkajs" is not tested by community CITGM runs.
(2): The module "swagger-editor" depends on the "argparse@2.0.1" package which is under the non-acceptable license "Python-2.0". - ERROR
(3): The module "swagger-editor" depends on the "tslib@1.14.1" package which is under the non-acceptable license "0BSD". - ERROR
(4): The module "swagger-editor" does not specify the engines field or package-support.json, so we cannot determine if it supports the LTS versions of Node.js.
(5): The module "swagger-editor" seems to have no available TypeScript typings.
(6): The module "swagger-editor" is not tested by community CITGM runs.
(7): 0 medium risk vulnerabilities found.
```
> feat: small readability improvement on the summary

- src/plugins/resolved.js
Example output:
```
(1): The module "a-foo-module" does not specify the engines field or package-support.json, so we cannot determine if it supports the LTS versions of Node.js.
(2): The module "a-foo-module" seems to have no available TypeScript typings.
(3): The module "a-foo-module" is not tested by community CITGM runs.
(4): The module "a-foo-module" has more dependencies (including sub-dependencies) than the default "1".  <---- 
```
Related to #84 
We are using 20 as default for now according with the issue created
> feat: add a check for a default number of dependencies

- src/lib/network.js
- src/plugins/audit.js
- test/plugins/audit.test.js
This commit updates the audit plugin to use GitHub's security advisory
database instead of npm's. GitHub's advisory database is based on
GraphQL and also requires an authentication token to be specified to be
used. Currently, a warning will be displayed if the user has not
specified this token:
```console
$ node index.js
NPCheck Report
(1): The Audit plugin requires a GitHub Token to be specified using
--github-token, or a GITHUB_TOKEN environment variable
problems: 1 (errors: 0 - warnings: 1)
```
> Use GitHub Advisory Database instead of npm's

- package-lock.json
- src/lib/network.js
- src/lib/regex.js
post was only used by audit plugin. Since
post was used with same graphql url but options
to specify the query any cached value would
result in incorrect result from previous query.
Remove caching so that we get the right answer
for each request.
Signed-off-by: Michael Dawson <mdawson@devrus.com>
> fix: remove caching on network post
